### ISSUE TITLE
Mandrill adapter, ** (ArgumentError) argument error (and fix)

### ISSUE THREAD

**Issue by pmontrasio** [swoosh/swoosh#168]
We run out of mails in the test plan on Mandrill and it started rejecting messages with `"status": "invalid"`. This is normal but the adapter throws this error

```
     ** (ArgumentError) argument error
     stacktrace:
       :erlang.iolist_to_binary(%{"_id" => "...", "email" => "mymail@example.com", "reject_reason" => nil, "status" => "invalid"})
       (poison) lib/poison/parser.ex:35: Poison.Parser.parse/2
       (poison) lib/poison/parser.ex:51: Poison.Parser.parse!/2
       (poison) lib/poison.ex:83: Poison.decode!/2
       (swoosh) lib/swoosh/adapters/mandrill.ex:46: Swoosh.Adapters.Mandrill.interpret_response/1
       ...
```

Line 46 is the last one of

```
  defp interpret_response(body) when is_binary(body), do: body |> Poison.decode! |> hd |> interpret_response
  defp interpret_response(%{"status" => "sent"} = body), do: {:ok, %{id: body["_id"]}}
  defp interpret_response(%{"status" => "queued"} = body), do: {:ok, %{id: body["_id"]}}
  defp interpret_response(%{"status" => "rejected"} = body), do: {:error, body}
  defp interpret_response(body), do: {:error, Poison.decode!(body)}
```

The error is caused because `body`, which is a map, is eventually passed to `:erlang.iolist_to_binary` which expects a binary and not a map.

The fix is not to `decode!` `body`, because it's already decoded:

```
  defp interpret_response(body), do: {:error, body}
```

**Comment by princemaple** [comment]
Hi @pmontrasio 

Thanks for reporting!
Your fix looks right. You could have sent a PR :)

I'll go ahead and send a fix.
❤️

**Comment by stevedomin** [comment]
Thanks for reporting @pmontrasio, this is now fixed and a new release will go out tomorrow.
