### ISSUE TITLE
key :adapter not found in: [otp_app: :my_web]

### ISSUE THREAD

**Issue by jpinnix** [swoosh/swoosh#334]
I just installed Swoosh and followed the instructions. I'm getting the following exception: `** (KeyError) key :adapter not found in: [otp_app: :my_web]`

Any ideas what could cause this?

Complete error and the config from config.exs below.

```elixir
[error] #PID<0.884.0> running MyWeb.Endpoint (connection #PID<0.883.0>, stream id 1) terminated
Server: localhost:4000 (http)
Request: POST /session
** (exit) an exception was raised:
    ** (KeyError) key :adapter not found in: [otp_app: :my_web]
        (elixir) lib/keyword.ex:377: Keyword.fetch!/2
        (swoosh) lib/swoosh/mailer.ex:115: Swoosh.Mailer.deliver/2
        (pow) lib/extensions/email_confirmation/phoenix/controllers/controller_callbacks.ex:39: PowEmailConfirmation.Phoenix.ControllerCallbacks.halt_unconfirmed/3
        (elixir) lib/enum.ex:1899: Enum."-reduce/3-lists^foldl/2-0-"/3
        (pow) lib/pow/phoenix/controllers/controller.ex:90: Pow.Phoenix.Controller.action/3
        (pow) lib/pow/phoenix/controllers/session_controller.ex:1: Pow.Phoenix.SessionController.action/2
        (pow) lib/pow/phoenix/controllers/session_controller.ex:1: Pow.Phoenix.SessionController.phoenix_controller_pipeline/2
        (my_web) lib/my_web/endpoint.ex:1: MyWeb.Endpoint.instrument/4
        (phoenix) lib/phoenix/router.ex:275: Phoenix.Router.__call__/1
        (my_web) lib/my_web/endpoint.ex:1: MyWeb.Endpoint.plug_builder_call/2
        (my_web) lib/plug/debugger.ex:122: MyWeb.Endpoint."call (overridable 3)"/2
        (my_web) lib/my_web/endpoint.ex:1: MyWeb.Endpoint.call/2
```

config.exs:
```elixir
config :my_web, MyWeb.Mailer,
  adapter: Swoosh.Adapters.AmazonSES,
  region: {:system, "SES_SERVER"},
  access_key: {:system, "SMTP_USERNAME"},
  secret: {:system, "SMTP_PASSWORD"}
```

**Comment by princemaple** [comment]
Hi,

Is your otp app really `:my_web` not `:pow`? Is your `Mailer` `MyWeb.Mailer` or `Pow.Mailer`?

**Comment by APB9785** [comment]
I'm having the exact same issue, but the module name is definitely not wrong.
```
# config/config.exs
config :my_app, MyApp.Mailer,
  adapter: Swoosh.Adapters.Mailjet,
  api_key: mailjet_api_key,
  secret: mailjet_secret_key
```

```
# lib/my_app/mailer.ex
defmodule MyApp.Mailer do
  use Swoosh.Mailer, otp_app: :my_app
end
```

**Comment by APB9785** [comment]
I was able to workaround by editing
```
# lib/my_app/mailer.ex
defmodule MyApp.Mailer do
  use Swoosh.Mailer, otp_app: :my_app, adapter: Swoosh.Adapters.Mailjet
end
```

**Comment by princemaple** [comment]
If you are sure all the spelling is correct, please report a new issue.
Relevant code is at https://github.com/swoosh/swoosh/blob/main/lib/swoosh/mailer.ex#L135-L148

**Comment by princemaple** [comment]
https://github.com/swoosh/swoosh/issues/590
