### ISSUE TITLE
Mailgun deliver creates Jason error

### ISSUE THREAD

**Issue by birdnestman** [swoosh/swoosh#343]
Hello

I got an error when I want to send emails with Mailgun adapter. Any idea what I've done wrong?

`
PhoenixInterface.MailGenerator.welcome(%{name: "simon", email: "simon@test.com"}) |> PhoenixInterface.Mailer.deliver
** (Jason.DecodeError) unexpected byte at position 0: 0x4D ('M')
    (jason) lib/jason.ex:78: Jason.decode!/2
    (swoosh) lib/swoosh/adapters/mailgun.ex:39: Swoosh.Adapters.Mailgun.deliver/2
`

**Comment by princemaple** [comment]
Hi, could you share your `welcome` implementation and its according template?

**Comment by birdnestman** [comment]
Sure:
```elixie
defmodule PhoenixInterface.Mailer do
  use Swoosh.Mailer, otp_app: :phoenix_interface
end

```
```elixir
defmodule PhoenixInterface.MailGenerator do
	import Swoosh.Email

  def welcome(user) do
    new()
    |> to({user.name, user.email})
    |> from({"Dr B Banner", "hulk.smash@example.com"})
    |> subject("Hello, Avengers!")
    |> html_body("<h1>Hello #{user.name}</h1>")
    |> text_body("Hello #{user.name}\n")
  end
end
```

**Comment by princemaple** [comment]
Hi, looks like you ran into a case where mailing returns some error and the adapter is not handling it well. Could you set a break point at Jason.decode!

**Comment by princemaple** [comment]
Sorry posted it by accident before finishing typing.

**Comment by birdnestman** [comment]
The output is `"Mailgun Magnificent API"` and that's why it crashes. This is no json format...

**Comment by princemaple** [comment]
A quick google search suggets that you could have made a mistake in either your api access key or the domain. Could you double check?

**Comment by jfreeze** [comment]
What domain is it looking for here?

This?    domain: "api.mailgun.net"
