### ISSUE TITLE
(KeyError) key :adapter not found in: [otp_app: :app_name]

### ISSUE THREAD

**Issue by Kapeusz** [swoosh/swoosh#432]
Hello! I just installed Swoosh and Pow, followed instructions on how to set up EmailConfirmation and PasswordReset. I'm getting the following exception: 
`(KeyError) key :adapter not found in: [otp_app: :shop]` 
when I'm trying to reset password/create a new account - anything about sending an email.

Does someone have any idea on what is causing this?

Here is full error screen.
```
** (exit) an exception was raised:
    ** (KeyError) key :adapter not found in: [otp_app: :shop]
        (elixir) lib/keyword.ex:377: Keyword.fetch!/2
        (swoosh) lib/swoosh/mailer.ex:115: Swoosh.Mailer.deliver/2
        (shop) lib/shop_web/templates/pow/pow_mailer.ex:21: ShopWeb.PowMailer.process/1
        (pow) lib/extensions/reset_password/phoenix/controllers/reset_password_controller.ex:34: PowResetPassword.Phoenix.ResetPasswordController.respond_create/1
        (pow) lib/extensions/reset_password/phoenix/controllers/reset_password_controller.ex:1: PowResetPassword.Phoenix.ResetPasswordController.action/2
        (pow) lib/extensions/reset_password/phoenix/controllers/reset_password_controller.ex:1: PowResetPassword.Phoenix.ResetPasswordController.phoenix_controller_pipeline/2
        (phoenix) lib/phoenix/router.ex:288: Phoenix.Router.__call__/2
        (shop) lib/shop_web/endpoint.ex:1: ShopWeb.Endpoint.plug_builder_call/2
        (shop) lib/plug/debugger.ex:122: ShopWeb.Endpoint."call (overridable 3)"/2
        (shop) lib/shop_web/endpoint.ex:1: ShopWeb.Endpoint.call/2
        (phoenix) lib/phoenix/endpoint/cowboy2_handler.ex:42: Phoenix.Endpoint.Cowboy2Handler.init/4
        (cowboy) f:/FYP 201920/Shop/shop/deps/cowboy/src/cowboy_handler.erl:41: :cowboy_handler.execute/2
        (cowboy) f:/FYP 201920/Shop/shop/deps/cowboy/src/cowboy_stream_h.erl:320: :cowboy_stream_h.execute/3
        (cowboy) f:/FYP 201920/Shop/shop/deps/cowboy/src/cowboy_stream_h.erl:302: :cowboy_stream_h.request_process/3
        (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
```
I'll attach any code needed.

**Comment by princemaple** [comment]
Hi, I don't know Pow. If you are using swoosh, you need an adaptor. What is your email provider? And what does your mailer code look like?

**Comment by Kapeusz** [comment]
My email provider is sendgrid. 
pow_mailer.ex

```
defmodule ShopWeb.PowMailer do

  use Pow.Phoenix.Mailer
  use Swoosh.Mailer, otp_app: :shop
  import Swoosh.Email

  require Logger

  @impl true
  def cast(%{user: user, subject: subject, text: text, html: html}) do
    %Swoosh.Email{}
    |> to({"", user.email})
    |> from({"Shop", "admin@shoptest.com"})
    |> subject(subject)
    |> html_body(html)
    |> text_body(text)
  end

  @impl true
  def process(email) do
    email
    |> deliver()
    |> log_warnings()
  end

  defp log_warnings({:error, reason}) do
    Logger.warn("Mailer backend failed with: #{inspect(reason)}")
  end

  defp log_warnings({:ok, response}), do: {:ok, response}
end
```

config.exs
```
  config :shop, :pow,
    user: Shop.Users.User,
    repo: Shop.Repo,
    mailer_backend: ShopWeb.PowMailer
```
prod.exs
```
config :shop, MyAppWeb.PowMailer,
  adapter: Swoosh.Adapters.Sendgrid,
  api_key: "SG.x.x"
```

**Comment by Kapeusz** [comment]
My email provider is sendgrid. 
pow_mailer.ex

```
defmodule ShopWeb.PowMailer do

  use Pow.Phoenix.Mailer
  use Swoosh.Mailer, otp_app: :shop
  import Swoosh.Email

  require Logger

  @impl true
  def cast(%{user: user, subject: subject, text: text, html: html}) do
    %Swoosh.Email{}
    |> to({"", user.email})
    |> from({"Shop", "admin@shoptest.com"})
    |> subject(subject)
    |> html_body(html)
    |> text_body(text)
  end

  @impl true
  def process(email) do
    email
    |> deliver()
    |> log_warnings()
  end

  defp log_warnings({:error, reason}) do
    Logger.warn("Mailer backend failed with: #{inspect(reason)}")
  end

  defp log_warnings({:ok, response}), do: {:ok, response}
end
```

config.exs
```
  config :shop, :pow,
    user: Shop.Users.User,
    repo: Shop.Repo,
    mailer_backend: ShopWeb.PowMailer
```
prod.exs
```
config :shop, MyAppWeb.PowMailer,
  adapter: Swoosh.Adapters.Sendgrid,
  api_key: "SG.x.x"
```

**Comment by princemaple** [comment]
The adapter is only configured for prod, it would be missing in dev. You should config it in config.exs and replace it in test.exs if desired.

**Comment by princemaple** [comment]
Sorry, mis-click on phone. Didn't mean to close.
