### ISSUE TITLE
(KeyError) key :adapter not found in: [otp_app: :my_app]

### ISSUE THREAD

**Issue by APB9785** [swoosh/swoosh#590]
I just did a fresh install of Swoosh 
```
# mix.exs
defp deps do
    [
      ...
      {:swoosh, "~> 1.3.4"},
      {:hackney, "~> 1.17"}
    ]
  end
```
```
# config/config.exs
config :my_app, MyApp.Mailer,
  adapter: Swoosh.Adapters.Mailjet,
  api_key: mailjet_api_key,
  secret: mailjet_secret_key
```
```
# lib/my_app/mailer.ex
defmodule MyApp.Mailer do
  use Swoosh.Mailer, otp_app: :my_app
end
```
But when calling MyApp.Mailer.deliver/2 I received the error
```
[error] GenServer #PID<0.544.0> terminating
** (KeyError) key :adapter not found in: [otp_app: :my_app]
    (elixir 1.11.3) lib/keyword.ex:420: Keyword.fetch!/2
    (swoosh 1.3.4) lib/swoosh/mailer.ex:122: Swoosh.Mailer.deliver/2
    (my_app 0.3.1) lib/my_app_web/live/page_live.ex:111: MyAppWeb.PageLive.handle_event/3
    ...
```
I was able to workaround by editing
```
# lib/my_app/mailer.ex
defmodule MyApp.Mailer do
  use Swoosh.Mailer, otp_app: :my_app, adapter: Swoosh.Adapters.Mailjet
end
```

**Comment by APB9785** [comment]
After the workaround, emails were sent out, so api_key and secret must be loading OK from config.exs.  I don't know why the adapter is not also loading...

**Comment by princemaple** [comment]
Could you setup a minimal reproducible repo? It doesn't look right to me.
```
key :adapter not found in: [otp_app: :my_app] # <- this list should include api_key and secret if it was going to work.
```
I suspect that you missed a recompile somewhere.

**Comment by APB9785** [comment]
You must be right, because when I revert back to the pre-workaround code I showed in the OP, it is still working.

**Comment by princemaple** [comment]
Thanks for the confirmation!
