### ISSUE TITLE
function false.post/4 is undefined 

### ISSUE THREAD

**Issue by Zat42** [swoosh/swoosh#653]
### Describe the bug

I used `mix phx.gen.auth` to generate my users' logic. After setting up `Swoosh` with `Mailgun` adapter, when I try to register a new user, I get this error:
```
UndefinedFunctionError at POST /html/users/register
function false.post/4 is undefined (module false is not available)

(swoosh 1.5.2) lib/swoosh/adapters/mailgun.ex:50: Swoosh.Adapters.Mailgun.deliver/2
```

```
[error] #PID<0.727.0> running SampleAppWeb.Endpoint (connection #PID<0.698.0>, stream id 5) terminated
Server: localhost:4000 (http)
Request: POST /html/users/register
** (exit) an exception was raised:
    ** (UndefinedFunctionError) function false.post/4 is undefined (module false is not available)
        false.post(["https://api.mailgun.net/v3", "/", "sandboxd*********\.mailgun.org", "/messages"], [{"User-Agent", "swoosh/1.5.2"}, {"Authorization", "Basic *******"}, {"Content-Type", "application/x-www-form-urlencoded"}], "from=%22MyApp%22+%3Ccontact%40example.com%3E&subject=Confirmation+instructions&text=%0A%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%0A%0AHi+john.doe%2B6%40gmail.com%2C%0A%0AYou+can+confirm+your+account+by+visiting+the+URL+below%3A%0A%0Ahttp%3A%2F%2Flocalhost%3A4000%2Fhtml%2Fusers%2Fconfirm%************%0A%0AIf+you+didn%27t+create+an+account+with+us%2C+please+ignore+this.%0A%0A%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%3D%0A&to=john.doe%40gmail.com", %Swoosh.Email{assigns: %{}, attachments: [], bcc: [], cc: [], from: {"MyApp", "contact@example.com"}, headers: %{}, html_body: nil, private: %{}, provider_options: %{}, reply_to: nil, subject: "Confirmation instructions", text_body: "\n==============================\n\nHi john.doe@gmail.com,\n\nYou can confirm your account by visiting the URL below:\n\nhttp://localhost:4000/html/users/confirm/***********\n\nIf you didn't create an account with us, please ignore this.\n\n==============================\n", to: [{"", "john.doe@gmail.com"}]})
        (swoosh 1.5.2) lib/swoosh/adapters/mailgun.ex:50: Swoosh.Adapters.Mailgun.deliver/2
        (sample_app 0.1.0) lib/sample_app/mailer.ex:2: anonymous fn/2 in SampleApp.Mailer.instrument/3
        (telemetry 1.0.0) deps/telemetry/src/telemetry.erl:293: :telemetry.span/3
        (sample_app 0.1.0) lib/sample_app/accounts/user_notifier.ex:13: SampleApp.Accounts.UserNotifier.deliver/3
        (sample_app 0.1.0) lib/sample_app_web/controllers/html/user_registration_controller.ex:17: SampleAppWeb.Html.UserRegistrationController.create/2
        (sample_app 0.1.0) lib/sample_app_web/controllers/html/user_registration_controller.ex:1: SampleAppWeb.Html.UserRegistrationController.action/2
        (sample_app 0.1.0) lib/sample_app_web/controllers/html/user_registration_controller.ex:1: SampleAppWeb.Html.UserRegistrationController.phoenix_controller_pipeline/2
        (phoenix 1.6.5) lib/phoenix/router.ex:355: Phoenix.Router.__call__/2
        (sample_app 0.1.0) lib/sample_app_web/endpoint.ex:1: SampleAppWeb.Endpoint.plug_builder_call/2
        (sample_app 0.1.0) lib/plug/debugger.ex:136: SampleAppWeb.Endpoint."call (overridable 3)"/2
        (sample_app 0.1.0) lib/sample_app_web/endpoint.ex:1: SampleAppWeb.Endpoint.call/2
        (phoenix 1.6.5) lib/phoenix/endpoint/cowboy2_handler.ex:54: Phoenix.Endpoint.Cowboy2Handler.init/4
        (cowboy 2.9.0) deps/cowboy/src/cowboy_handler.erl:37: :cowboy_handler.execute/2
        (cowboy 2.9.0) deps/cowboy/src/cowboy_stream_h.erl:306: :cowboy_stream_h.execute/3
        (cowboy 2.9.0) deps/cowboy/src/cowboy_stream_h.erl:295: :cowboy_stream_h.request_process/3
        (stdlib 3.16.1) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
```

### Steps to Reproduce the Bug or Issue

**lib/sample_app/accounts/user_notifier.ex :**
```elixir
defmodule SampleApp.Accounts.UserNotifier do
  import Swoosh.Email

  # Delivers the email using the application mailer.
  defp deliver(recipient, subject, body) do
    email =
      new()
      |> to(recipient)
      |> from({"MyApp", "contact@example.com"})
      |> subject(subject)
      |> text_body(body)

    with {:ok, _metadata} <- SampleApp.Mailer.deliver(email) do
      {:ok, email}
    end
  end

  ...
end
```

**lib/sample_app/mailer.ex :**
```elixir
defmodule SampleApp.Mailer do
  use Swoosh.Mailer, otp_app: :sample_app
end
```

**config/config.exs :**
```elixir
config :go_nodle_io, SampleApp.Mailer,
  adapter: Swoosh.Adapters.Mailgun,
  api_key: System.get_env("MAILER_SECRET_KEY"),
  domain: System.get_env("MAILER_DOMAIN", "example.com"),
  base_url: System.get_env("MAILER_BASE_URL", "https://api.mailgun.net/v3")
```

**Env:**
```
MAILER_DOMAIN=sandbox********************************.mailgun.org
MAILER_SECRET_KEY=********************************-********-********
```

### Platform

- OTP: `Erlang/OTP 24 [erts-12.1.5] [source] [64-bit] [smp:20:20] [ds:20:20:10] [async-threads:1] [jit]`
- Elixir: `Elixir 1.13.0 (compiled with Erlang/OTP 24)`

### Additional context

I am pretty sure something is miss configured but I can't find it out by myself. Any idea?

**Comment by princemaple** [comment]
Hi, please install finch and remove the line about api_client: false in generated config.

**Comment by Zat42** [comment]
Thanks for your help.

Since I never used `Swoosh` / `Finch` before, I am not sure how configure this.

Beside updating `config/config.exs` :
```elixir
config :swoosh, :api_client, Swoosh.ApiClient.Finch

config :sample_app, SampleApp.Mailer,
  adapter: Swoosh.Adapters.Mailgun,
  api_key: System.get_env("MAILER_SECRET_KEY"),
  domain: System.get_env("MAILER_DOMAIN", "example.com"),
  base_url: System.get_env("MAILER_BASE_URL", "https://api.mailgun.net/v3")
```

And adding `{:finch, "~> 0.10"},` to `deps`, is there any things that I am missing?

Not sure how to follow documentation about "starting `Finch`" with `Phoenix`?

**Comment by princemaple** [comment]
Glad you figured it out! Feel free to ask questions if you get stuck again.
