### ISSUE TITLE
KeyError in gen_smtp when trying to deliver email with attachment through SMTP

### ISSUE THREAD

**Issue by kevinwong150** [swoosh/swoosh#703]
### Describe the bug

Situation:
Working on a function with phoenix and swoosh to send email with attachment of iCalendar file (.ics). The folllowing error shows up when I trying to `deliver()` the email with header updated by `header(email, "Content-Type", "multipart/alternative")`. See below section for detail steps to reproduce.

deps version: 
```
{:swoosh, "~> 1.7.1"},
{:phoenix_swoosh, "~> 1.0"},
{:gen_smtp, "~> 1.2.0"},
```

short error message:
```
** (KeyError) key :content_type_params not found in: %{}
```

### Steps to Reproduce the Bug or Issue

1. build attachment with:
```
attach = Swoosh.Attachment.new(
      {:data, "this is text attahment"},
      content_type: "text/plain",
      filename: "only_text.txt"
    )
```

2. build email then deliver:
```
email =
      new()
      |> from("steve.rogers@example.com")
      |> to("my_address@example.com")
      |> html_body("Text body then attachment")
      |> attachment(attach)
      |> header("Content-Type", "multipart/alternative")
      |> subject("test email subject")
      |> Mailer.deliver()
```

3. KeyError message shown in terminal:
```
** (KeyError) key :content_type_params not found in: %{}
    :erlang.map_get(:content_type_params, %{})
    (gen_smtp 1.2.0) path_to_projects/ultra/deps/gen_smtp/src/mimemail.erl:1020: :mimemail.encode_component/5
    (gen_smtp 1.2.0) path_to_projects/ultra/deps/gen_smtp/src/mimemail.erl:207: :mimemail.encode/2        
    (swoosh 1.7.1) lib/swoosh/adapters/smtp.ex:49: Swoosh.Adapters.SMTP.deliver/2
    (ultra 0.1.0) lib/ultra/mailer.ex:2: anonymous fn/2 in Ultra.Mailer.instrument/3
    (telemetry 1.1.0) c:/Users/wongkevi/Documents/projects/ultra/deps/telemetry/src/telemetry.erl:320: :telemetry.span/3      
    (ultra 0.1.0) lib/ultra_web/live/request_clients/client_list.ex:244: UltraWeb.RequestClients.ClientList.handle_event/3    
    (phoenix_live_view 0.17.10) lib/phoenix_live_view/channel.ex:600: anonymous fn/4 in Phoenix.LiveView.Channel.inner_component_handle_event/4
    (telemetry 1.1.0) c:/Users/wongkevi/Documents/projects/ultra/deps/telemetry/src/telemetry.erl:320: :telemetry.span/3      
    (phoenix_live_view 0.17.10) lib/phoenix_live_view/diff.ex:206: Phoenix.LiveView.Diff.write_component/4
    (phoenix_live_view 0.17.10) lib/phoenix_live_view/channel.ex:523: Phoenix.LiveView.Channel.component_handle_event/6       
    (stdlib 3.15) gen_server.erl:695: :gen_server.try_dispatch/4
    (stdlib 3.15) gen_server.erl:771: :gen_server.handle_msg/6
    (stdlib 3.15) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
```

note: if not adding attachment to email, i.e. comment out the line `|> attachment(attach)`, the email can be sent successfully

### Platform

- OTP: Erlang/OTP 22
- Elixir: Elixir 1.13.1

**Comment by princemaple** [comment]
Hi, could you give #704 a go?

**Comment by kevinwong150** [comment]
no luck, same error message

**Comment by princemaple** [comment]
Hi @kevinwong150 , you can fix your code by removing `|> header("Content-Type", "multipart/alternative")`. The header is automatically added depending on the content of the email.

`multipart/alternative` is incorrect for emails with attachments.

**Comment by princemaple** [comment]
Tested in livebook

# Untitled notebook

```elixir
Mix.install([
  :gen_smtp,
  :swoosh
])
```

## Section

```elixir
attach =
  Swoosh.Attachment.new(
    {:data, "this is text attahment"},
    content_type: "text/plain",
    filename: "only_text.txt"
  )
```

```elixir
defmodule Mailer do
  use Swoosh.Mailer, otp_app: :app, adapter: Swoosh.Adapters.SMTP, relay: "abc.test"
end
```

```elixir
import Swoosh.Email

email =
  new()
  |> from("steve.rogers@example.com")
  |> to("my_address@example.com")
  |> html_body("Text body then attachment")
  |> attachment(attach)
  |> subject("test email subject")
  |> Mailer.deliver()
```

**Comment by kevinwong150** [comment]
more background to my scenario:
in my application, the attachment will be an .ics file and the email will be sent to an outlook mailbox. But somehow the .ics file attachment will turn into "not supported calendar message.ics" in the email and not able to display as meeting invite in outlook.
Wrong behaviour:
![image](https://user-images.githubusercontent.com/13821768/180126227-7ce72351-f65a-4522-826a-6ba096b20eb3.png)
Expectation: 
![image](https://user-images.githubusercontent.com/13821768/180133262-df1346fd-ea10-4ded-81c7-44008986d5d3.png)

I did some research and found that the email header `Content-Type: multipart/alternative` seems to be relavant to this. So I thought header should be controllable when building the email, see comments from the below urls:

1. https://answers.microsoft.com/en-us/outlook_com/forum/all/outlook-started-to-show-ics-files-as-not-supported/028d434a-da59-48fd-b983-a85e32f690fe
> Make sure, 
> 
> 1) EMail is multipart alternative 
> 
> 2) First  attached text/html body and then ICS along with MIME. 
> 
> Order of attachment and MIME is very important. It won't work even if all mime are present until those are not in proper order 

2. https://docs.microsoft.com/en-us/answers/questions/805852/email-from-net-with-calendar-invite-and-file-attac.html

> The root cause of this problem is: When your email contain attachments, MailMessage will generate message like this:
> 
```
 multipart/mixed
   multipart/alternative
     text/plain
     text/calendar;method=REQUEST
   multipart/mixed
     content-type (with a content-disposition:attachment)
```
> But Outlook365 expect the message to be:
> 
```
 multipart/mixed
   multipart/alternative
     text/plain
     text/calendar;method=REQUEST
   content-type (with a content-disposition:attachment)
```
> When Outlook receive wrong attachment format. Some how, It'll ignore the calendar part.
> I think you can use MailKit instead of System.Net.Mail to send emails. By using this library, the message format can be controlled.

**Comment by princemaple** [comment]
Hi @kevinwong150 I updated this issue to be a feature, for future investigation. Sending ics as an alternative part to text and/or html is currently not supported. The closest you can get right now is sending an the ics as the sole attachment.

**Comment by arkadiyk** [comment]
I've done some investigation and found the working message format which goes into `:mimemail.encode({type, subtype, headers, %{}, parts},[])`

Here is the example:
```elixir
[type, subtype, headers, parts] = [
  "multipart",
  "alternative",
  [
    {"From", "arkadiyk@example.com"},
    {"To", "arkadiyk@example.com"},
    {"Subject", "Test Invite"},
    {"MIME-Version", "1.0"}
  ],
  [
    {"text", "html",
     [
       {"Content-Type", "text/html; charset=\"utf-8\""},
       {"Content-Transfer-Encoding", "quoted-printable"}
     ],
     %{
       content_type_params: [{"charset", "utf-8"}],
       disposition: "inline",
       disposition_params: []
     }, "<h1>Email Body</h1>"},
    {"text", "calendar", [{"Content-Transfer-Encoding", "7bit"}],
     %{
        content_type_params: [{"charset", "utf-8"}, {"name", "invite.ics"}, {"method", "REQUEST"}],
        disposition: "inline"
     },
   <<invite.ics content>>  
   }
  ]
]
```

The important attributes are: 
-   Content subtype should be `alternative`
-  `Content-Transfer-Encoding` should be `"7bit"`, not `"base64"`
-  `content_type_params` should contain `method=REQUEST`

**Comment by princemaple** [comment]
Woah. Thanks for the investigation!

**Comment by jiegillet** [comment]
Hello! I also had some issues with Outlook not recognizing my ics attachment, so I looked into it and I found that the default way to add attachments worked fine with the online version of Outlook (outlook.cloud.microsoft) as long as the method of the calendar invite was added to the `Content-Type`.
So I prepared a [PR to automatically add this method](https://github.com/swoosh/swoosh/compare/main...jiegillet:swoosh:jie-ics_attachment?expand=1), only to realize at the last moment that the same problem could be solved by adding custom headers to my attachment.
Since I did the work already, I though that I would ask if it's worth opening a PR. I checked that having both a custom header and having the method added automatically doesn't break the email.
